url: https://weaverbel.github.io/carpentriesblog/
baseurl: /carpentriesblog

# Site settings
title: The Carpentries
email: team@carpentries.org
description: "This is the joint blog of Software and Data Carpentry (The Carpentries)."


# Team names, titles and social links
people:
- name: Jonah Duckles
  pic: 1
  position: Executive Director, Software Carpentry
  social:
    - title: twitter
      url: https://twitter.com/jduckles
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Tracy Teal
  pic: 2
  position: Director, Data Carpentry
  social:
    - title: twitter
      url: https://twitter.com/jduckles
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Belinda Weaver
  pic: 3
  position: Community Development Lead
  social:
    - title: twitter
      url: https://twitter.com/cloudaus
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/swcarpentry
  - title: twitter
    url: http://twitter.com/datacarpentry
  - title: facebook
    url: https://www.facebook.com/carpentries
  - title: github
    url: http://github.com/carpentries


# Postal address (add as many lines as necessary)
address:
  - line: #
  - line: #

# Build settings
markdown: kramdown
permalink: pretty
